# Generated by Django 5.1.2 on 2024-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='core.CartItem', to='core.product'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
